#!/usr/bin/env python3
"""Generate cached OpenAI TTS MP3 files for a vocabulary study site."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


DEFAULT_INSTRUCTIONS = (
    "Speak clearly and naturally for an English vocabulary learner. "
    "Use a warm neutral American English accent, natural intonation, and a moderate pace."
)


def load_vocab_reader():
    script_path = Path(__file__).with_name("build_vocab_site.py")
    spec = importlib.util.spec_from_file_location("build_vocab_site", script_path)
    if spec is None or spec.loader is None:
        raise RuntimeError("Could not load build_vocab_site.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.read_vocab


def stable_name(prefix: str, text: str) -> str:
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:20]
    return f"{prefix}-{digest}.mp3"


def create_speech(
    *,
    text: str,
    output_path: Path,
    api_key: str,
    model: str,
    voice: str,
    instructions: str,
    overwrite: bool,
) -> None:
    if output_path.exists() and not overwrite:
        return
    payload = {
        "model": model,
        "voice": voice,
        "input": text,
        "instructions": instructions,
        "response_format": "mp3",
    }
    req = urllib.request.Request(
        "https://api.openai.com/v1/audio/speech",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=60) as response:
            output_path.write_bytes(response.read())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"TTS request failed for {text!r}: HTTP {exc.code} {detail}") from exc


def relpath(path: Path, base: Path) -> str:
    return path.relative_to(base).as_posix()


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", help="Vocabulary CSV/XLSX generated by netease_lyrics_vocab.py")
    parser.add_argument("--site-dir", default="vocab-study-site", help="Study site directory containing index.html")
    parser.add_argument("--audio-dir", default="audio", help="Audio directory relative to --site-dir")
    parser.add_argument("--manifest", default="audio_manifest.json", help="Manifest path relative to --site-dir")
    parser.add_argument("--model", default="gpt-4o-mini-tts", help="OpenAI TTS model")
    parser.add_argument("--voice", default="cedar", help="OpenAI TTS voice, for example cedar or marin")
    parser.add_argument("--instructions", default=DEFAULT_INSTRUCTIONS, help="Voice style instructions")
    parser.add_argument("--max-items", type=int, help="Limit number of vocabulary rows to generate")
    parser.add_argument("--include-examples", action="store_true", help="Also generate audio for example sentences")
    parser.add_argument("--max-examples", type=int, default=3, help="Max examples per word when --include-examples is set")
    parser.add_argument("--overwrite", action="store_true", help="Regenerate existing MP3 files")
    parser.add_argument("--sleep", type=float, default=0.05, help="Delay between requests")
    args = parser.parse_args(argv)

    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is required to generate model-based TTS audio.")

    read_vocab = load_vocab_reader()
    rows = read_vocab(Path(args.input))
    if args.max_items:
        rows = rows[: args.max_items]

    site_dir = Path(args.site_dir)
    audio_dir = site_dir / args.audio_dir
    audio_dir.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, Any] = {
        "provider": "openai",
        "model": args.model,
        "voice": args.voice,
        "disclosure": "Audio generated by AI text-to-speech.",
        "words": {},
        "examples": {},
    }

    for row in rows:
        word = row["word"]
        word_path = audio_dir / stable_name("word", word)
        create_speech(
            text=word,
            output_path=word_path,
            api_key=api_key,
            model=args.model,
            voice=args.voice,
            instructions=args.instructions,
            overwrite=args.overwrite,
        )
        manifest["words"][word] = relpath(word_path, site_dir)

        if args.include_examples:
            example_paths: list[str] = []
            for example in row.get("examples", [])[: args.max_examples]:
                example_path = audio_dir / stable_name("example", f"{word}\n{example}")
                create_speech(
                    text=example,
                    output_path=example_path,
                    api_key=api_key,
                    model=args.model,
                    voice=args.voice,
                    instructions=args.instructions,
                    overwrite=args.overwrite,
                )
                example_paths.append(relpath(example_path, site_dir))
                if args.sleep:
                    time.sleep(args.sleep)
            manifest["examples"][word] = example_paths

        if args.sleep:
            time.sleep(args.sleep)

    manifest_path = site_dir / args.manifest
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"words={len(manifest['words'])}")
    print(f"examples={sum(len(items) for items in manifest['examples'].values())}")
    print(f"manifest={manifest_path}")
    print("Rebuild the study page with:")
    print(f"python3 scripts/build_vocab_site.py {args.input} --output {site_dir / 'index.html'} --audio-manifest {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
